services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: frontend:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - frontend-network
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: backend:latest
    restart: always
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_DB_TYPE=${FLASK_DB_TYPE}
      - FLASK_DB_USER=${FLASK_DB_USER}
      - FLASK_DB_NAME=${FLASK_DB_NAME}
      - FLASK_DB_PASSWORD=${FLASK_DB_PASSWORD}
      - FLASK_DB_HOST=${FLASK_DB_HOST}
      - FLASK_DB_PORT=${FLASK_DB_PORT}
    expose:
    - "5000"
    deploy:
      replicas: 2
    networks:
      - frontend-network
      - db-network
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    networks:
      - db-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  frontend-network:
  db-network:

volumes:
  postgres_data: