services:
  frontend:
    build:
      context: ./front
    restart: always
    ports:
      - "80:80"
    networks:
      - frontend-network
    depends_on:
      - backend

  backend:
    build:
      context: ./back
    restart: always
    expose:
    - "5000"
    deploy:
      replicas: 2
    networks:
      - frontend-network
      - db-network
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    expose:
      - "5432"
    networks:
      - db-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  frontend-network:
  db-network:

volumes:
  postgres_data: